name: CI/CD FastAPI + Terraform Fase 1

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run FastAPI tests
      run: |
        pytest app/tests

    - name: Build Docker image
      run: |
        docker build -t fastapi-app:latest app

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5  # o la versión que prefieras

    - name: Terraform Init & Apply
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
      # No se necesitan variables de entorno de AWS,
      # Terraform detecta automáticamente las credenciales desde ~/.aws

    - name: Set S3_BUCKET_NAME env var
      run: |
        cd infra
        BUCKET_NAME=$(terraform output -raw bucket_name)
        echo "S3_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Run Infrastructure Tests (S3)
      run: |
        pytest app/tests
      # boto3 también detecta automáticamente las credenciales desde ~/.aws
      env:
        S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
